# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'client_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63lient_service.proto\x12\x0e\x63lient_service\"4\n\x0eMessageRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t\"(\n\x13\x43lientStatusRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x8d\x01\n\x14\x43lientStatusResponse\x12\x44\n\x08statuses\x18\x01 \x03(\x0b\x32\x32.client_service.ClientStatusResponse.StatusesEntry\x1a/\n\rStatusesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xbd\x01\n\rClientService\x12N\n\x0bSendMessage\x12\x1e.client_service.MessageRequest\x1a\x1f.client_service.MessageResponse\x12\\\n\x0fGetClientStatus\x12#.client_service.ClientStatusRequest\x1a$.client_service.ClientStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTSTATUSRESPONSE_STATUSESENTRY']._loaded_options = None
  _globals['_CLIENTSTATUSRESPONSE_STATUSESENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGEREQUEST']._serialized_start=40
  _globals['_MESSAGEREQUEST']._serialized_end=92
  _globals['_MESSAGERESPONSE']._serialized_start=94
  _globals['_MESSAGERESPONSE']._serialized_end=142
  _globals['_CLIENTSTATUSREQUEST']._serialized_start=144
  _globals['_CLIENTSTATUSREQUEST']._serialized_end=184
  _globals['_CLIENTSTATUSRESPONSE']._serialized_start=187
  _globals['_CLIENTSTATUSRESPONSE']._serialized_end=328
  _globals['_CLIENTSTATUSRESPONSE_STATUSESENTRY']._serialized_start=281
  _globals['_CLIENTSTATUSRESPONSE_STATUSESENTRY']._serialized_end=328
  _globals['_CLIENTSERVICE']._serialized_start=331
  _globals['_CLIENTSERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
